#!/usr/bin/env ruby
# frozen_string_literal: true

source_path = File.dirname(__dir__)
$LOAD_PATH.unshift(source_path)

editor = ENV['EDITOR'] || 'vi'

abort("You must supply a type ('hardware' or 'software').") unless ARGV[0].match?(/^(hardware|software)$/)

abort('You must provide a name.') if ARGV[1].nil?

type = ARGV[0]
name = ARGV[1..-1].join(' ')
slug = name.downcase.tr(' ', '-')

prefix = slug[0].match?(/[a-z]/) ? slug[0] : '0'
path = File.join(source_path, 'gear', type, prefix, "#{slug}.json")

abort("Entry already exists for '#{slug}'.") unless Dir.glob(path.gsub(type, '**')).empty?

name.gsub!(/(iOS|Android)$/, '(\1)')

entry = <<ENTRY
{
  "name": "#{name}",
  "description": "",
  "url": ""
}
ENTRY

File.open(path, 'w') do |f|
  f.write(entry)
end

exec("#{editor} #{path}")
