#!/usr/bin/env ruby
# frozen_string_literal: true

source_path = File.dirname(__dir__)
$LOAD_PATH.unshift(source_path)

require 'lib/usesthis/api'

config_path = File.join(source_path, 'config.json')
config = JSON.parse(File.read(config_path), symbolize_names: true)

puts 'Building API...'

UsesThis::API.generate('.', config[:destination])

puts 'Done!'
