#!/usr/bin/env ruby

source_path = File.dirname(__dir__)
$:.unshift(source_path)

require 'lib/usesthis'

config = YAML::load_file('./config.yml')

site = UsesThis::Site.new(config)
api = UsesThis::API.new(site)

begin
  site.generate
  api.generate
rescue Exception => e
  puts "Error: #{e}"
end