#!/usr/bin/env ruby
# frozen_string_literal: true

source_path = File.dirname(__dir__)
$LOAD_PATH.unshift(source_path)

require "lib/usesthis/api"

build_path = (ARGV[0] ? ARGV[0] : File.join(source_path, "api"))

UsesThis::API.generate(build_path)
