#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.dirname(__dir__))

require_relative '../lib/usesthis'

config = YAML.safe_load_file('config.yml', symbolize_names: true)
UsesThis.generate(config: config)
