#!/usr/bin/env ruby

require 'date'

source_path = File.dirname(__dir__)

$:.unshift(source_path)

abort("You must supply a name for the interviewee.") if ARGV.length < 2

name = ARGV.join(' ')
slug = name.downcase.gsub(/ /, '.')

date = Time.now.to_date
found_day = false

while !found_day
  if date.strftime('%a') =~ /Tue|Thu/
    found_day = true
  else
    date = date.next_day
  end
end

file_path = File.join(source_path, 'posts', "#{date.strftime('%Y-%m-%d')}-#{slug}.interview")
abort("Interview already exists for #{slug}.") if File.exists?(file_path)

output = <<OUTPUT
---
name: #{name}
summary: (summary)
categories:
- (category)
- (category)
---

#### Who are you, and what do you do?

#### What hardware do you use?

#### And what software?

#### What would be your dream setup?

OUTPUT

File.open(file_path, 'w') do |file|
  file.write(output)
end

`open #{file_path}`