#!/usr/bin/env ruby

source_path = File.dirname(__dir__)
$:.unshift(source_path)

require 'lib/usesthis'
require 'date'

abort("You must supply a name for the interviewee.") if ARGV.length < 2

name = ARGV.join(' ')
slug = name.downcase.gsub(/ /, '.')

interviews = Dir.glob(File.join(source_path, 'posts', '*.markdown'))
latest_date = File.basename(interviews.reverse.first).match(/\d{4}-\d{2}-\d{2}/)[0]
next_date = Date.parse(latest_date).next_day

loop do
  break if next_date.strftime('%a') =~ /Tue|Thu/
  next_date = next_date.next_day
end

file_path = File.join(source_path, 'posts', "#{next_date.strftime('%Y-%m-%d')}-#{slug}.markdown")
abort("Interview already exists for #{slug}.") if File.exists?(file_path)

output = <<OUTPUT
---
title: #{name}
summary: (summary)
categories:
- (category)
- (category)
---

#### Who are you, and what do you do?

#### What hardware do you use?

#### And what software?

#### What would be your dream setup?

OUTPUT

File.open(file_path, 'w') do |file|
  file.write(output)
end

`subl ~/Development/usesthis && subl #{file_path}`