#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

abort('You must supply an interview!') unless ARGV[0]&.end_with?('.markdown')

gear_pattern = /\[([^\[\(\)]+)\]\[([a-z0-9\.\-]+)?\]/

contents = File.read(ARGV[0])
slugs = contents.scan(gear_pattern).map { |link| link[1] || link[0].downcase }

links = []

glob_path = File.join(
  File.dirname(__dir__),
  'gear',
  '**',
  '*.json'
)

Dir.glob(glob_path).sort.each do |path|
  slug = File.basename(path, '.json')
  next unless slugs.include?(slug)

  gear = JSON.parse(File.read(path))
  links << "[#{slug}]: #{gear['url']} \"#{gear['description']}\"\n"
end

return if links.empty?

contents.gsub!(/\[.+\]: http(.+)\n/, '')

File.write(ARGV[0], contents.strip << "\n\n#{links.join}")
