#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/usesthis'

abort('You must supply an interview!') unless ARGV[0]&.end_with?('.markdown')

contents = File.read(ARGV[0])
slugs = UsesThis.match_gear_slugs(contents)

links = []

glob_path = File.join(File.dirname(__dir__), 'data', 'gear', '**', '*.json')

Dir.glob(glob_path).sort.each do |path|
  slug = File.basename(path, '.json')
  next unless slugs.include?(slug)

  gear = JSON.parse(File.read(path))
  links << "[#{slug}]: #{gear['url']} \"#{gear['description']}\"\n"
end

return if links.empty?

contents.gsub!(/\[.+\]: http(.+)\n/, '')

File.write(ARGV[0], contents.strip << "\n\n#{links.sort.join}")
