#!/usr/bin/env ruby
# frozen_string_literal: true

source_path = File.dirname(__dir__)
$LOAD_PATH.unshift(source_path)

require "dimples"

build_path = (ARGV[0] ? ARGV[0] : File.join(source_path, "build"))

Dimples::Site.generate(build_path)
