#!/usr/bin/env ruby
# frozen_string_literal: true

source_path = File.dirname(__dir__)
$LOAD_PATH.unshift(source_path)

require "dimples"
require "lib/usesthis/api"

Dimples::Site.generate(File.join(source_path, "site"))
UsesThis::API.generate(File.join(source_path, "api"))
