#!/usr/bin/env ruby

trap('SIGINT') { exit! }

source_path = File.dirname(__dir__)
$LOAD_PATH.unshift(source_path)

require 'yaml'
require 'faraday'

type = ARGV[0]

abort("Usage: #{__dir__}/scan [gear|links]") unless type =~ /^(gear|links)$/

files = case type
        when 'gear'
          File.join(source_path, 'gear', '**', '*.yml')
        when 'links'
          File.join(source_path, 'links', '**', '*.yml')
        end

puts 'Scanning:'

Dir.glob(files) do |path|
  data = YAML.load_file(path)
  original_url = data['url']

  print "- #{data['name']}: "

  response = Faraday.get(data['url'])
  new_url = response.headers['location']

  case response.status
  when 200
    puts 'All good.'
  when 301, 308
    unless new_url =~ %r{/^https?:\/\//}
      uri = Faraday.URI(original_url)
      new_url = "#{uri.scheme}://#{uri.host}#{new_url}"
    end

    data['url'] = new_url
    puts 'Updated (redirected).'
  when 302, 307
    puts 'Temporary redirect - ignoring.'
  when 404
    data['error'] = 'Dead link'
  else
    puts "Unexpected status (#{response.status})!"
  end

  if data['url'] != original_url.to_s || data['error']
    File.open(path, 'w') do |file|
      file.write(YAML.dump(data))
    end
  end
end
